### ISSUE TITLE
conditional offset of content depending if navbar is active or not

### ISSUE THREAD

**Issue by fearthedear** [tunamonster/Muzufit#4]

**Comment by fearthedear** [comment]
closed because sidebar will be replaced by slide-out sidebar

**Comment by fearthedear** [comment]
can be easily fixed as css files are now working, waiting for jquery issue to be solved then will be pushed to master

**Comment by tunamonster** [comment]
can't find the jquery issue? What is it

**Comment by fearthedear** [comment]
@tunamonster the jquery issue is what I sent you in the Screenshot yesterday on face. Is it specific to my computer? 

Kind regards, 

Linus Kinzel 
+31628771662

**Comment by fearthedear** [comment]
finally fixed this motherfuck
