### ISSUE TITLE
create landing page

### ISSUE THREAD

**Issue by fearthedear** [tunamonster/Muzufit#7]
should include:
- catchy text
- parallax scrolling of fitness images
- (video header?)

**Comment by fearthedear** [comment]
landing page created. needs content

**Comment by tunamonster** [comment]
Can you push it with fake content? http://www.rubydoc.info/github/stympy/faker/Faker/Lorem 
Gem is already installed

**Comment by fearthedear** [comment]
@tunamonster I pushed it with some random content already you can check it out by switching to the branch 

Kind regards, 

Linus Kinzel 
+31628771662
